mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import study_spaces
from mysite import views as mysite_views
from study_spaces import views

urlpatterns = [
    path('', mysite_views.home),
    path('admin/', admin.site.urls),
    path('study/', include("study_spaces.urls")),
    path('study/accounts/', include("allauth.urls")),
]

study_spaces/urls.py
from django.urls import path

from . import views


app_name = "study_spaces"
urlpatterns = [
    path("", views.home, name="homepage"),
    path("logout", views.logout_view, name="logout"),
    path("logout/", views.logout_view, name="logout"),
    path('login', views.login_view, name="login"),
    path('admin', views.admin_view, name="admin"),
    path('directions', views.directions, name="directions"),
    path('profile', views.profile, name='profile'),
    path('submission', views.submission, name='submission'),
    path('approve', views.approve_submission, name='approve'),
    path('deny', views.deny_submission, name='deny'),
    path('information', views.information, name='information'),
    path('edit/<int:study_space_id>/', views.edit_study_space, name='edit'),
    path('delete/<int:study_space_id>/', views.delete_study_space, name='delete'),
]

study_spaces/models.py
"""
 REFERENCES

 Title: Python String format() Method
 Author: W3 Schools
 Date: N/A
 Code version: N/A
 URL: https://www.w3schools.com/python/ref_string_format.asp
 Software License: N/A

 Title: Model field reference
 Author: Django Project
 Date: N/A
 Code version: N/A
 URL: https://docs.djangoproject.com/en/4.2/ref/models/fields/
 Software License: N/A
 """

from django.db import models
from django.utils import timezone


class StudySpace(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    latitude = models.FloatField(default=0.0)
    longitude = models.FloatField(default=0.0)

    # Amenities
    has_wifi = models.BooleanField(default=False)
    has_outlets = models.BooleanField(default=False)
    has_printers = models.BooleanField(default=False)
    has_whiteboards = models.BooleanField(default=False)
    is_quiet = models.BooleanField(default=False)
    is_outside = models.BooleanField(default=False)
    has_food = models.BooleanField(default=False)

    class ApprovalStatus(models.IntegerChoices):
        APPROVED = 1
        PENDING = 0
        DENIED = -1

    approved_submission = models.IntegerField(choices=ApprovalStatus.choices, default=ApprovalStatus.PENDING)
    user_email = models.CharField(max_length=200)
    denial_reason = models.CharField(max_length=200, default='')
    location = models.TextField(default='')
    environment = models.TextField(default='')
    traffic = models.TextField(default='')
    hours = models.TextField(default='')
    other_information = models.TextField(default='')
    time_created = models.DateTimeField(default=timezone.now)

    def get_sentence(self):
        return "{name} is located at {address}.".format(name=self.name, address=self.address)

    def __str__(self):
        return self.name

study_spaces/views.py
"""
 REFERENCES

 Title: Items in JSON object are out of order using "json.dumps"?
 Author: jfs
 Date: 12/20/2017
 Code version: N/A
 URL: https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps
 Software License: N/A
 
 Title: Lambda Sorted in Python - How to Lambda Sort a List
 Author: Kolade Chris
 Date: 03/16/2023
 Code version: N/A
 URL: https://www.freecodecamp.org/news/lambda-sort-list-in-python/
 Software License: N/A
 """


from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.conf import settings
from .mixins import Directions
import json

from .models import *


def is_admin(email):
    admins = [
        'lukecreech11@gmail.com',
        'rqf8pe@virginia.edu',
        'gracefly4@gmail.com',
        'ethanhaller02@gmail.com',
        'cs3240.super@gmail.com',
        'projecta06testuser@gmail.com'
    ]

    return email in admins


def get_approved_spaces():
    return StudySpace.objects.filter(approved_submission=StudySpace.ApprovalStatus.APPROVED)


def get_pending_spaces():
    return StudySpace.objects.filter(approved_submission=StudySpace.ApprovalStatus.PENDING)


def get_spaces_by_email(email):
    return StudySpace.objects.filter(user_email=email).order_by('-time_created')


@login_required(login_url='/study/login')
def home(request):
    mod = get_approved_spaces()
    mod_json = json.dumps(list(mod.values('latitude', 'longitude', 'id', 'name')))
    context = {
        'mod': mod,
        'mod_json': mod_json,
        'key': settings.GOOGLE_API_KEY,
    }
    return render(request, "study_spaces/studyspaces.html", context)


def logout_view(request):
    logout(request)
    return redirect("/study/")


@login_required(login_url='/study/login')
def directions(request):
    mod_json = []
    s = None
    if "dest" in request.GET:
        s = StudySpace.objects.get(pk=request.GET["dest"])
        s = {'latitude': s.latitude, 'longitude': s.longitude, 'id': s.id, 'name': s.name, 'address': s.address}
        mod_json = json.dumps(s)

    lat_a = request.GET.get("lat_a")
    long_a = request.GET.get("long_a")
    lat_b = request.GET.get("lat_b")
    long_b = request.GET.get("long_b")
    directions = None
    showDirections = False
    if lat_a and long_a and lat_b and long_b:
        directions = Directions(
            lat_a=lat_a,
            long_a=long_a,
            lat_b=lat_b,
            long_b=long_b,
        )
        showDirections = True
    context = {
        's': s,
        'mod_json': mod_json,
        'key': settings.GOOGLE_API_KEY,
        'directions': directions,
        'showDirections': showDirections,
        "origin": f'{lat_a}, {long_a}',
        "destination": f'{lat_b}, {long_b}'
    }
    return render(request, 'study_spaces/directions.html', context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect("/study")
    else:
        return render(request, "study_spaces/login.html")


@login_required(login_url='/study/login')
def admin_view(request):
    if is_admin(request.user.email):
        return render(request, "study_spaces/admin.html")
    else:
        return redirect('/study')


@login_required(login_url='/study/login')
def profile(request):
    return render(request, 'study_spaces/profile.html')


@login_required(login_url='/study/login')
def submission(request):
    context = {"google_api_key": settings.GOOGLE_API_KEY}
    context["toasts"] = [str(message) for message in messages.get_messages(request) if not str(message).startswith("Successfully signed in")]

    if is_admin(request.user.email):
        context["pending_list"] = get_pending_spaces()
        context["pending_list_length"] = len(context["pending_list"])
        context["approved_list"] = get_approved_spaces()
        context["approved_list_length"] = len(context["approved_list"])
        return render(request, 'study_spaces/approval.html', context)
    else:
        context["submitted_list"] = get_spaces_by_email(request.user.email)
        if request.method == 'POST':
            if request.POST["name"] == '':
                context["error_message"] = "Please input a name."
                return render(request, 'study_spaces/submission.html', context)
            if request.POST["address"] == '' or request.POST["lat"] == '' or request.POST["long"] == '':
                context["error_message"] = "Please input a valid address."
                return render(request, 'study_spaces/submission.html', context)

            s = StudySpace(
                name=request.POST["name"],
                address=request.POST["address"],
                latitude=request.POST["lat"],
                longitude=request.POST["long"],
                user_email=request.user.email,
                has_wifi = 'has_wifi' in request.POST,
                has_outlets = 'has_outlets' in request.POST,
                has_printers = 'has_printers' in request.POST,
                has_whiteboards = 'has_whiteboards' in request.POST,
                is_quiet = 'is_quiet' in request.POST,
                is_outside = 'is_outside' in request.POST,
                has_food = 'has_food' in request.POST,
                location=request.POST["location"],
                environment=request.POST["environment"],
                traffic=request.POST["traffic"],
                hours=request.POST["hours"],
                other_information=request.POST["other_information"],
                denial_reason = 'None'
            )
            s.save()
            messages.success(request, f'Study Space "{s.name}" has been successfully submitted.')
        context["submitted_list"] = get_spaces_by_email(request.user.email)
        context["submitted_list_length"] = len(context["submitted_list"])
        return render(request, 'study_spaces/submission.html', context)


@login_required(login_url='/study/login')
def approve_submission(request):
    if request.method == 'POST':
        s = StudySpace.objects.get(pk=request.POST["id"])
        s.approved_submission = StudySpace.ApprovalStatus.APPROVED
        s.save()
        messages.success(request, f'Study Space "{s.name}" has been successfully approved.')
    return redirect('/study/submission')


@login_required(login_url='/study/login')
def deny_submission(request):
    if request.method == 'POST':
        s = StudySpace.objects.get(pk=request.POST["id"])
        s.approved_submission = StudySpace.ApprovalStatus.DENIED
        s.denial_reason = request.POST["Denial"]
        s.save()
        messages.success(request, f'Study Space "{s.name}" has been successfully denied.')
    return redirect('/study/submission')


@login_required(login_url='/study/login')
def edit_study_space(request, study_space_id):
    if is_admin(request.user.email):
        space = StudySpace.objects.get(pk=study_space_id)
        context = {"study_space": space, "google_api_key": settings.GOOGLE_API_KEY}

        if request.method == 'POST':
            if request.POST["name"] == '':
                context["error_message"] = "Please input a name."
                return render(request, 'study_spaces/edit.html', context)
            if request.POST["address"] == '' or request.POST["lat"] == '' or request.POST["long"] == '':
                context["error_message"] = "Please input a valid address."
                return render(request, 'study_spaces/edit.html', context)

            space.name=request.POST["name"]
            space.address=request.POST["address"]
            space.latitude=request.POST["lat"]
            space.longitude=request.POST["long"]
            space.has_wifi= 'has_wifi' in request.POST
            space.has_outlets = 'has_outlets' in request.POST
            space.has_printers = 'has_printers' in request.POST
            space.has_whiteboards = 'has_whiteboards' in request.POST
            space.is_quiet = 'is_quiet' in request.POST
            space.is_outside = 'is_outside' in request.POST
            space.has_food = 'has_food' in request.POST
            space.location = request.POST["location"]
            space.environment = request.POST["environment"]
            space.traffic = request.POST["traffic"]
            space.hours = request.POST["hours"]
            space.other_information=request.POST["other_information"]
            space.approved_submission = StudySpace.ApprovalStatus.APPROVED
            space.denial_reason = 'None'
            space.save()
            messages.success(request, f'Saved changed to Study Space "{space.name}".')
            return redirect('/study/submission')
        return render(request, 'study_spaces/edit.html', context)
    return redirect('/study')


@login_required(login_url='/study/login')
def delete_study_space(request, study_space_id):
    if request.method == 'POST':
        try:
            space_to_delete = StudySpace.objects.get(pk=study_space_id)
            space_to_delete.delete()
            messages.success(request, f'Study Space "{space_to_delete.name}" has been successfully deleted.')
        except StudySpace.DoesNotExist:
            messages.error(request, 'Study Space does not exist.')

    return redirect('/study/submission')


@login_required(login_url='/study/login')
def information(request):
    context = {}
    if "dest" in request.GET:
        s = StudySpace.objects.get(pk=request.GET["dest"])
        context["study_space"] = s
    return render(request, 'study_spaces/information.html', context)

study_spaces/templates/study_spaces/approval.html
<!--
	REFERENCES:

	 Title: How can I use multiple submit buttons in an HTML form?
	 Author: tutorialspoint
	 Date: updated on 10/4/2023
	 Code version: N/A
	 URL: https://www.tutorialspoint.com/How-can-I-use-multiple-submit-buttons-in-an-HTML-form
	 Software License: N/A

	 Title: Making Django Messages Work with Bootstrap Toast: A Guide
	 Author: Cody Smith
	 Date: published 05/20/2023
	 Code version: N/A
	 URL: https://copyprogramming.com/howto/django-messages-bootstrap-toast-how-to-make-it-work
	 Software License: N/A

	 Title: Bootstrap v5.0: Toasts
	 Author: Bootstrap
	 Date: accessed 12/01/2023
	 Code version: N/A
	 URL: https://getbootstrap.com/docs/5.0/components/toasts/
	 Software License: MIT

	 Title: Bootstrap v5.0: Modal
	 Author: Bootstrap
	 Date: accessed 12/01/2023
	 Code version: N/A
	 URL: https://getbootstrap.com/docs/5.0/components/modal/
	 Software License: MIT
-->

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Study Space Approval</title>

		{% load static %} {% load bootstrap_icons %}
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script>
			$(document).ready(function () {
				$(".toast").toast()
				$(".toast").toast("show")
			})
		</script>
	</head>

	<body class="background">
		{% include 'study_spaces/navbar.html' %} {% if toasts %}
		<div id="toast-container" class="toast-container position-fixed end-0 m-3">
			{% for message in toasts %}
			<div class="toast align-items-center text-white bg-success" role="alert" aria-live="assertive" aria-atomic="true">
				<div class="d-flex">
					<div class="toast-body">{{ message | safe }}</div>
					<button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
				</div>
			</div>
			{% endfor %}
		</div>
		{% endif %}
		<div class="container-fluid mx-0 px-0">
			<div class="row m-auto">
				<div id="approve-submission-column" class="col-lg-6 mt-4 mb-3 mx-auto" style="overflow-y: scroll">
					<h3 class="mt-5 mb-3">Approve Submissions</h3>
					{% if pending_list_length == 0 %}
					<p>No pending submissions</p>
					{% endif %} {% for x in pending_list %}
					<form method="post" class="form-multiline submission-section p-3 mb-3">
						{% csrf_token %}
						<span class="d-flex">
							<strong>Study Space Name:</strong>
							<p class="mx-2">{{ x.name }}</p>
						</span>
						<span class="d-flex">
							<strong>Address:</strong>
							<p class="mx-2">{{ x.address }}</p>
						</span>
						<span class="d-flex flex-column">
							<strong>Amenities:</strong>
							<span class="px-3">
								{% if x.has_wifi %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has WiFi">
									{% bs_icon 'wifi' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if x.has_outlets %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has Outlets">
									{% bs_icon 'outlet' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if x.has_printers %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has Printers">
									{% bs_icon 'printer' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if x.has_whiteboards %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has Whiteboards">
									{% bs_icon 'easel' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if x.is_quiet %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Quiet Study Space">
									{% bs_icon 'bell-slash' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if x.is_outside %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Outdoor Study Space">
									{% bs_icon 'sun' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if x.has_food %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Food Nearby">
									{% bs_icon 'cup' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %}
							</span>
						</span>
						<style>
							.mb-2 p {
								max-width: 100%;
								overflow: auto;
								overflow-x: wrap;
								white-space: normal;
							}
						</style>
						<div class="mb-2">
							<strong>Location:</strong>
							<p class="mx-2">{{ x.location }}</p>
							<strong>Environment:</strong>
							<p class="mx-2">{{ x.environment }}</p>
							<strong>Traffic:</strong>
							<p class="mx-2">{{ x.traffic }}</p>
							<strong>Hours:</strong>
							<p class="mx-2">{{ x.hours }}</p>
							<strong>Other Information:</strong>
							<p class="mx-2">{{ x.other_information }}</p>
						</div>
						<label for="denial-reason"><stron>Reason for Denial (if applicable):</stron></label>
						<textarea id="denial-reason" name="Denial" class="form-control w-100"></textarea>
						<br />
						<input type="hidden" name="id" value="{{ x.id }}" />
						<input type="submit" value="Approve" formaction="{% url 'study_spaces:approve' %}" class="btn btn-success" />
						<input type="submit" value="Deny" formaction="{% url 'study_spaces:deny' %}" class="btn btn-danger" />
						<br />
					</form>
					{% endfor %}
				</div>

				<div id="past-approved-submission-column" class="col-lg-5 mt-4 mb-3 mx-auto" style="overflow-y: scroll">
					<h3 class="mt-5 mb-3">Approved Study Spaces</h3>
					{% for y in approved_list %}
					<div class="mb-3 p-3 submission-section">
						<span class="d-flex">
							<strong>Study Space Name:</strong>
							<p class="mx-2">{{ y.name }}</p>
						</span>
						<span class="d-flex">
							<strong>Address:</strong>
							<p class="mx-2">{{ y.address }}</p>
						</span>
						<span class="d-flex flex-column">
							<strong>Amenities:</strong>
							<span class="px-3">
								{% if y.has_wifi %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has WiFi">
									{% bs_icon 'wifi' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if y.has_outlets %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has Outlets">
									{% bs_icon 'outlet' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if y.has_printers %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has Printers">
									{% bs_icon 'printer' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if y.has_whiteboards %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Has Whiteboards">
									{% bs_icon 'easel' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if y.is_quiet %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Quiet Study Space">
									{% bs_icon 'bell-slash' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if y.is_outside %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Outdoor Study Space">
									{% bs_icon 'sun' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %} {% if y.has_food %}
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="Food Nearby">
									{% bs_icon 'cup' size='1.75em' extra_classes='feature-icon' %}
								</span>
								{% endif %}
							</span>
						</span>
						<span class="d-flex justify-content-end">
							<a href="{% url 'study_spaces:edit' y.id %}" class="btn secondary mx-1">Edit</a>
							<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ y.id }}">Delete</button>

							<div
								class="modal fade"
								id="deleteModal{{ y.id }}"
								tabindex="-1"
								role="dialog"
								aria-labelledby="deleteModalLabel"
								aria-hidden="true"
							>
								<div class="modal-dialog modal-dialog-centered" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
											<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
										</div>
										<div class="modal-body">
											<p>Are you sure you want to delete the study space "{{ y.name }}"?</p>
										</div>
										<form method="post" action="{% url 'study_spaces:delete' y.id %}">
											{% csrf_token %}
											<input type="hidden" name="id" value="{{ y.id }}" />
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
												<input type="submit" value="Delete" class="btn btn-danger" />
											</div>
										</form>
									</div>
								</div>
							</div>
						</span>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</body>
</html>

study_spaces/templates/study_spaces/navbar.html
<!--
REFERENCES

 Title: Navbar
 Author: Bootstrap
 Date: N/A
 Code version: N/A
 URL: https://getbootstrap.com/docs/4.0/components/navbar/
 Software License: MIT
-->

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>NavBar</title>

		{% load static %} {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
		<link rel="stylesheet" type="text/css" href="{% static 'theme.css' %}" />
	</head>
	<body class="primary">
		<nav id="global-navbar" class="navbar navbar-expand-lg primary top-0" style="position: sticky; z-index: 2000;">
			<div class="container-fluid">
				<h1 class="navbar-brand m-2">UVAStudySpaces</h1>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarTogglerDemo02"
					aria-controls="navbarTogglerDemo02"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<p class="nav-link nav-item my-0">Menu</p>
				</button>
				<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item mx-2 my-1">
							<a class="nav-link {% if request.path == '/study/' %}nav-active{% endif %}" href="/study/">Home</a>
						</li>
						<li class="nav-item mx-2 my-1">
							<a class="nav-link {% if '/directions' in request.path %}nav-active{% endif %}" href="{% url 'study_spaces:directions' %}">Directions</a>
						</li>
						<li class="nav-item mx-2 my-1">
							<a class="nav-link {% if '/submission' in request.path %}nav-active{% endif %}" href="/study/submission">{% if is_admin %}Approve Submissions{% else %}Submit a Study Space{% endif %}</a>
						</li>
					</ul>
					<div class="nav-item dropdown float-end mx-2 py-1">
						<a class="dropdown-toggle d-flex align-items-center h-100" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<span class="profile-name mx-2">Hello, {{ googleUser.name }}</span>
							<img src="{{ googleUser.picture }}" alt="User Profile Picture" class="profile-picture" />
						</a>
						<ul class="dropdown-menu dropdown-menu-end primary" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item nav-link" href="{% url 'study_spaces:profile' %}">Profile</a></li>
							<li><hr class="dropdown-divider" /></li>
							<li><a class="dropdown-item nav-link" href="{% url 'study_spaces:logout' %}">Logout</a></li>
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</body>
</html>

study_spaces/templates/study_spaces/studyspaces.html
<!--
REFERENCES

 Title: Tooltips
 Author: Bootstrap
 Date: N/A
 Code version: N/A
 URL: https://getbootstrap.com/docs/5.0/components/tooltips/
 Software License: MIT
-->

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Study Spaces</title>

		{% load bootstrap_icons %}
		<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
		<script
			src="https://code.jquery.com/jquery-3.6.0.min.js"
			integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			crossorigin="anonymous"
		></script>
		<script>
			window.map
			window.key = "{{key}}"
			window.modJson = JSON.parse("{{ mod_json|escapejs }}")
		</script>
		{% load static %}
		<script src="{% static 'home_map.js' %}"></script>
	</head>
	<body class="background">
		{% include 'study_spaces/navbar.html' %}
		<div class="row" style="width: 100vw">
			<div class="col-sm-8">
				<div id="map-container">
					<div id="map" class="h-100"></div>
				</div>
			</div>
			<div class="col-sm-4">
				<div id="list-container" class="my-4" style="overflow-y: scroll">
					{% block content %} {% for x in mod %}
					<div id="study-card-id-{{x.id}}" class="card mb-3" style="border-width: 2px; border-style: solid">
						<div class="card-body">
							<h5 class="card-title">{{x.name}}</h5>
							<p class="card-text m-0">{{x.address}}</p>
							<div style="margin: 0.5em 0px 0.5em 0px;">
								<span>
									{% if x.has_wifi %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="WiFi">
										{% bs_icon 'wifi' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %} {% if x.has_outlets %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="Outlets">
										{% bs_icon 'outlet' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %} {% if x.has_printers %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="Printers">
										{% bs_icon 'printer' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %} {% if x.has_whiteboards %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="Whiteboards">
										{% bs_icon 'easel' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %} {% if x.is_quiet %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="Quiet">
										{% bs_icon 'bell-slash' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %} {% if x.is_outside %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="Outside">
										{% bs_icon 'sun' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %} {% if x.has_food %}
									<span class="icon-tooltip" data-toggle="tooltip" data-placement="bottom" title="Food Nearby">
										{% bs_icon 'cup' size='1.75em' extra_classes='feature-icon' %}
									</span>
									{% endif %}
								</span>
							</div>
							<div class="float-end">
								<a href="{% url 'study_spaces:information' %}?dest={{ x.id }}" class="btn outline-primary">More Information</a>
								<a href="{% url 'study_spaces:directions' %}?dest={{ x.id }}" class="btn primary-button">Get Directions</a>
							</div>
						</div>
					</div>
					{% endfor %} {% endblock content %}
				</div>
			</div>
		</div>
	</body>
</html>